title: Digi-Kunst.nrw
description: Informationen für Partnerhochschulen
theme: just-the-docs

url: https://digi-kunst.github.io/Handreichung/

aux_links:
  Template Repository: https://github.com/Digi-Kunst/Handreichung
